// Cross-check the JS calculator port against the Python reference (py_golden.json,
// generated by running src/scoring/calculator.py over every mock patient).
import { describe, it, expect } from "vitest";
import { readFileSync, readdirSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FHIRClient } from "../src/fhir/fhirClient.js";
import { calculateAll } from "../src/scoring/calculator.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const MOCK_DIR = resolve(__dirname, "..", "..", "data", "mock");
const golden = JSON.parse(readFileSync(resolve(__dirname, "py_golden.json"), "utf-8"));

function deriveSummary(file) {
  const ctx = FHIRClient.fromFile(resolve(MOCK_DIR, file)).buildPatientContext();
  const calc = calculateAll(ctx);
  return {
    map: calc.map.value,
    qsofa: calc.qsofa.total,
    qsofa_pos: calc.qsofa.positive,
    sofa: calc.sofa.total,
    news2: calc.news2.total,
    news2_risk: calc.news2.risk_level,
    news2_scale: calc.news2.scale,
    egfr: calc.egfr.egfr,
    egfr_stage: calc.egfr.stage,
    alerts: (calc.summary.alerts || []).length,
  };
}

describe("calculator parity with Python reference", () => {
  for (const [file, expected] of Object.entries(golden)) {
    it(`matches Python golden for ${file}`, () => {
      expect(deriveSummary(file)).toEqual(expected);
    });
  }
});
